name: Deploy to Remote Server

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/containeryard/openssh
      env:
        SSH_HOST: ${{ vars.SSH_HOST }}
        SSH_KNOWN_HOSTS: ${{ vars.SSH_KNOWN_HOSTS }}
        SSH_USER_NAME: ${{ vars.SSH_USER_NAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      volumes:
          - ./:/app/
    steps:
      - name: TEST 1
        run: cat ~/.ssh/config
      - name: Copy HTML to Remote Server
        run: echo $SSH_KNOWN_HOSTS && scp splash-page.html $SSH_USER_NAME@$SSH_HOST:/home1/mountash/www/peregian-free-wifi/index.html
      - name: TEST 2
        run: cat ~/.ssh/config